title: mdocUI
description: Generative UI library for LLMs using Markdoc tag syntax inline with markdown prose
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
color_scheme: dark
aux_links:
  GitHub: https://github.com/mdocui/mdocui
  npm: https://www.npmjs.com/org/mdocui
